name: country_code_picker
description: A language picker dialog. 
version: 3.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  recase: ^4.1.0
  diacritic: ^0.1.6

flutter:
  assets:
    - flags/
