name: country_code_picker
description: A flutter package for showing a country code selector. In addition it gives the possibility to select a list of favorites countries, as well as to search using a simple searchbox  
version: 3.0.0
homepage: https://github.com/imtoori/CountryCodePicker

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  recase: ^4.1.0
  diacritic: ^0.1.6

flutter:
  assets:
    - flags/
