// This is a generated file.

import 'package:country_code_picker/cities.dart';

import 'AD.g.dart';
import 'AE.g.dart';
import 'AF.g.dart';
import 'AG.g.dart';
import 'AI.g.dart';
import 'AL.g.dart';
import 'AM.g.dart';
import 'AO.g.dart';
import 'AR.g.dart';
import 'AS.g.dart';
import 'AT.g.dart';
import 'AU.g.dart';
import 'AW.g.dart';
import 'AX.g.dart';
import 'AZ.g.dart';
import 'BA.g.dart';
import 'BB.g.dart';
import 'BD.g.dart';
import 'BE.g.dart';
import 'BF.g.dart';
import 'BG.g.dart';
import 'BH.g.dart';
import 'BI.g.dart';
import 'BJ.g.dart';
import 'BL.g.dart';
import 'BM.g.dart';
import 'BN.g.dart';
import 'BO.g.dart';
import 'BQ.g.dart';
import 'BR.g.dart';
import 'BS.g.dart';
import 'BT.g.dart';
import 'BW.g.dart';
import 'BY.g.dart';
import 'BZ.g.dart';
import 'CA.g.dart';
import 'CC.g.dart';
import 'CD.g.dart';
import 'CF.g.dart';
import 'CG.g.dart';
import 'CH.g.dart';
import 'CI.g.dart';
import 'CK.g.dart';
import 'CL.g.dart';
import 'CM.g.dart';
import 'CN.g.dart';
import 'CO.g.dart';
import 'CR.g.dart';
import 'CU.g.dart';
import 'CV.g.dart';
import 'CW.g.dart';
import 'CX.g.dart';
import 'CY.g.dart';
import 'CZ.g.dart';
import 'DE.g.dart';
import 'DJ.g.dart';
import 'DK.g.dart';
import 'DM.g.dart';
import 'DO.g.dart';
import 'DZ.g.dart';
import 'EC.g.dart';
import 'EE.g.dart';
import 'EG.g.dart';
import 'EH.g.dart';
import 'ER.g.dart';
import 'ES.g.dart';
import 'ET.g.dart';
import 'FI.g.dart';
import 'FJ.g.dart';
import 'FK.g.dart';
import 'FM.g.dart';
import 'FO.g.dart';
import 'FR.g.dart';
import 'GA.g.dart';
import 'GB.g.dart';
import 'GD.g.dart';
import 'GE.g.dart';
import 'GF.g.dart';
import 'GG.g.dart';
import 'GH.g.dart';
import 'GI.g.dart';
import 'GL.g.dart';
import 'GM.g.dart';
import 'GN.g.dart';
import 'GP.g.dart';
import 'GQ.g.dart';
import 'GR.g.dart';
import 'GS.g.dart';
import 'GT.g.dart';
import 'GU.g.dart';
import 'GW.g.dart';
import 'GY.g.dart';
import 'HK.g.dart';
import 'HN.g.dart';
import 'HR.g.dart';
import 'HT.g.dart';
import 'HU.g.dart';
import 'ID.g.dart';
import 'IE.g.dart';
import 'IL.g.dart';
import 'IM.g.dart';
import 'IN.g.dart';
import 'IQ.g.dart';
import 'IR.g.dart';
import 'IS.g.dart';
import 'IT.g.dart';
import 'JE.g.dart';
import 'JM.g.dart';
import 'JO.g.dart';
import 'JP.g.dart';
import 'KE.g.dart';
import 'KG.g.dart';
import 'KH.g.dart';
import 'KI.g.dart';
import 'KM.g.dart';
import 'KN.g.dart';
import 'KP.g.dart';
import 'KR.g.dart';
import 'KW.g.dart';
import 'KY.g.dart';
import 'KZ.g.dart';
import 'LA.g.dart';
import 'LB.g.dart';
import 'LC.g.dart';
import 'LI.g.dart';
import 'LK.g.dart';
import 'LR.g.dart';
import 'LS.g.dart';
import 'LT.g.dart';
import 'LU.g.dart';
import 'LV.g.dart';
import 'LY.g.dart';
import 'MA.g.dart';
import 'MC.g.dart';
import 'MD.g.dart';
import 'ME.g.dart';
import 'MF.g.dart';
import 'MG.g.dart';
import 'MH.g.dart';
import 'MK.g.dart';
import 'ML.g.dart';
import 'MM.g.dart';
import 'MN.g.dart';
import 'MO.g.dart';
import 'MP.g.dart';
import 'MQ.g.dart';
import 'MR.g.dart';
import 'MS.g.dart';
import 'MT.g.dart';
import 'MU.g.dart';
import 'MV.g.dart';
import 'MW.g.dart';
import 'MX.g.dart';
import 'MY.g.dart';
import 'MZ.g.dart';
import 'NA.g.dart';
import 'NC.g.dart';
import 'NE.g.dart';
import 'NF.g.dart';
import 'NG.g.dart';
import 'NI.g.dart';
import 'NL.g.dart';
import 'NO.g.dart';
import 'NP.g.dart';
import 'NR.g.dart';
import 'NU.g.dart';
import 'NZ.g.dart';
import 'OM.g.dart';
import 'PA.g.dart';
import 'PE.g.dart';
import 'PF.g.dart';
import 'PG.g.dart';
import 'PH.g.dart';
import 'PK.g.dart';
import 'PL.g.dart';
import 'PM.g.dart';
import 'PN.g.dart';
import 'PR.g.dart';
import 'PS.g.dart';
import 'PT.g.dart';
import 'PW.g.dart';
import 'PY.g.dart';
import 'QA.g.dart';
import 'RE.g.dart';
import 'RO.g.dart';
import 'RS.g.dart';
import 'RU.g.dart';
import 'RW.g.dart';
import 'SA.g.dart';
import 'SB.g.dart';
import 'SC.g.dart';
import 'SD.g.dart';
import 'SE.g.dart';
import 'SG.g.dart';
import 'SH.g.dart';
import 'SI.g.dart';
import 'SJ.g.dart';
import 'SK.g.dart';
import 'SL.g.dart';
import 'SM.g.dart';
import 'SN.g.dart';
import 'SO.g.dart';
import 'SR.g.dart';
import 'SS.g.dart';
import 'ST.g.dart';
import 'SV.g.dart';
import 'SX.g.dart';
import 'SY.g.dart';
import 'SZ.g.dart';
import 'TC.g.dart';
import 'TD.g.dart';
import 'TF.g.dart';
import 'TG.g.dart';
import 'TH.g.dart';
import 'TJ.g.dart';
import 'TL.g.dart';
import 'TM.g.dart';
import 'TN.g.dart';
import 'TO.g.dart';
import 'TR.g.dart';
import 'TT.g.dart';
import 'TV.g.dart';
import 'TW.g.dart';
import 'TZ.g.dart';
import 'UA.g.dart';
import 'UG.g.dart';
import 'US.g.dart';
import 'UY.g.dart';
import 'UZ.g.dart';
import 'VA.g.dart';
import 'VC.g.dart';
import 'VE.g.dart';
import 'VG.g.dart';
import 'VI.g.dart';
import 'VN.g.dart';
import 'VU.g.dart';
import 'WF.g.dart';
import 'WS.g.dart';
import 'XK.g.dart';
import 'YE.g.dart';
import 'YT.g.dart';
import 'ZA.g.dart';
import 'ZM.g.dart';
import 'ZW.g.dart';

class CityCountryReflector{
  List<City> operator [](String key) {
    switch (key) {
      case 'AD': return AD;
      case 'AE': return AE;
      case 'AF': return AF;
      case 'AG': return AG;
      case 'AI': return AI;
      case 'AL': return AL;
      case 'AM': return AM;
      case 'AO': return AO;
      case 'AR': return AR;
      case 'AS': return AS;
      case 'AT': return AT;
      case 'AU': return AU;
      case 'AW': return AW;
      case 'AX': return AX;
      case 'AZ': return AZ;
      case 'BA': return BA;
      case 'BB': return BB;
      case 'BD': return BD;
      case 'BE': return BE;
      case 'BF': return BF;
      case 'BG': return BG;
      case 'BH': return BH;
      case 'BI': return BI;
      case 'BJ': return BJ;
      case 'BL': return BL;
      case 'BM': return BM;
      case 'BN': return BN;
      case 'BO': return BO;
      case 'BQ': return BQ;
      case 'BR': return BR;
      case 'BS': return BS;
      case 'BT': return BT;
      case 'BW': return BW;
      case 'BY': return BY;
      case 'BZ': return BZ;
      case 'CA': return CA;
      case 'CC': return CC;
      case 'CD': return CD;
      case 'CF': return CF;
      case 'CG': return CG;
      case 'CH': return CH;
      case 'CI': return CI;
      case 'CK': return CK;
      case 'CL': return CL;
      case 'CM': return CM;
      case 'CN': return CN;
      case 'CO': return CO;
      case 'CR': return CR;
      case 'CU': return CU;
      case 'CV': return CV;
      case 'CW': return CW;
      case 'CX': return CX;
      case 'CY': return CY;
      case 'CZ': return CZ;
      case 'DE': return DE;
      case 'DJ': return DJ;
      case 'DK': return DK;
      case 'DM': return DM;
      case 'DO': return DO;
      case 'DZ': return DZ;
      case 'EC': return EC;
      case 'EE': return EE;
      case 'EG': return EG;
      case 'EH': return EH;
      case 'ER': return ER;
      case 'ES': return ES;
      case 'ET': return ET;
      case 'FI': return FI;
      case 'FJ': return FJ;
      case 'FK': return FK;
      case 'FM': return FM;
      case 'FO': return FO;
      case 'FR': return FR;
      case 'GA': return GA;
      case 'GB': return GB;
      case 'GD': return GD;
      case 'GE': return GE;
      case 'GF': return GF;
      case 'GG': return GG;
      case 'GH': return GH;
      case 'GI': return GI;
      case 'GL': return GL;
      case 'GM': return GM;
      case 'GN': return GN;
      case 'GP': return GP;
      case 'GQ': return GQ;
      case 'GR': return GR;
      case 'GS': return GS;
      case 'GT': return GT;
      case 'GU': return GU;
      case 'GW': return GW;
      case 'GY': return GY;
      case 'HK': return HK;
      case 'HN': return HN;
      case 'HR': return HR;
      case 'HT': return HT;
      case 'HU': return HU;
      case 'ID': return ID;
      case 'IE': return IE;
      case 'IL': return IL;
      case 'IM': return IM;
      case 'IN': return IN;
      case 'IQ': return IQ;
      case 'IR': return IR;
      case 'IS': return IS;
      case 'IT': return IT;
      case 'JE': return JE;
      case 'JM': return JM;
      case 'JO': return JO;
      case 'JP': return JP;
      case 'KE': return KE;
      case 'KG': return KG;
      case 'KH': return KH;
      case 'KI': return KI;
      case 'KM': return KM;
      case 'KN': return KN;
      case 'KP': return KP;
      case 'KR': return KR;
      case 'KW': return KW;
      case 'KY': return KY;
      case 'KZ': return KZ;
      case 'LA': return LA;
      case 'LB': return LB;
      case 'LC': return LC;
      case 'LI': return LI;
      case 'LK': return LK;
      case 'LR': return LR;
      case 'LS': return LS;
      case 'LT': return LT;
      case 'LU': return LU;
      case 'LV': return LV;
      case 'LY': return LY;
      case 'MA': return MA;
      case 'MC': return MC;
      case 'MD': return MD;
      case 'ME': return ME;
      case 'MF': return MF;
      case 'MG': return MG;
      case 'MH': return MH;
      case 'MK': return MK;
      case 'ML': return ML;
      case 'MM': return MM;
      case 'MN': return MN;
      case 'MO': return MO;
      case 'MP': return MP;
      case 'MQ': return MQ;
      case 'MR': return MR;
      case 'MS': return MS;
      case 'MT': return MT;
      case 'MU': return MU;
      case 'MV': return MV;
      case 'MW': return MW;
      case 'MX': return MX;
      case 'MY': return MY;
      case 'MZ': return MZ;
      case 'NA': return NA;
      case 'NC': return NC;
      case 'NE': return NE;
      case 'NF': return NF;
      case 'NG': return NG;
      case 'NI': return NI;
      case 'NL': return NL;
      case 'NO': return NO;
      case 'NP': return NP;
      case 'NR': return NR;
      case 'NU': return NU;
      case 'NZ': return NZ;
      case 'OM': return OM;
      case 'PA': return PA;
      case 'PE': return PE;
      case 'PF': return PF;
      case 'PG': return PG;
      case 'PH': return PH;
      case 'PK': return PK;
      case 'PL': return PL;
      case 'PM': return PM;
      case 'PN': return PN;
      case 'PR': return PR;
      case 'PS': return PS;
      case 'PT': return PT;
      case 'PW': return PW;
      case 'PY': return PY;
      case 'QA': return QA;
      case 'RE': return RE;
      case 'RO': return RO;
      case 'RS': return RS;
      case 'RU': return RU;
      case 'RW': return RW;
      case 'SA': return SA;
      case 'SB': return SB;
      case 'SC': return SC;
      case 'SD': return SD;
      case 'SE': return SE;
      case 'SG': return SG;
      case 'SH': return SH;
      case 'SI': return SI;
      case 'SJ': return SJ;
      case 'SK': return SK;
      case 'SL': return SL;
      case 'SM': return SM;
      case 'SN': return SN;
      case 'SO': return SO;
      case 'SR': return SR;
      case 'SS': return SS;
      case 'ST': return ST;
      case 'SV': return SV;
      case 'SX': return SX;
      case 'SY': return SY;
      case 'SZ': return SZ;
      case 'TC': return TC;
      case 'TD': return TD;
      case 'TF': return TF;
      case 'TG': return TG;
      case 'TH': return TH;
      case 'TJ': return TJ;
      case 'TL': return TL;
      case 'TM': return TM;
      case 'TN': return TN;
      case 'TO': return TO;
      case 'TR': return TR;
      case 'TT': return TT;
      case 'TV': return TV;
      case 'TW': return TW;
      case 'TZ': return TZ;
      case 'UA': return UA;
      case 'UG': return UG;
      case 'US': return US;
      case 'UY': return UY;
      case 'UZ': return UZ;
      case 'VA': return VA;
      case 'VC': return VC;
      case 'VE': return VE;
      case 'VG': return VG;
      case 'VI': return VI;
      case 'VN': return VN;
      case 'VU': return VU;
      case 'WF': return WF;
      case 'WS': return WS;
      case 'XK': return XK;
      case 'YE': return YE;
      case 'YT': return YT;
      case 'ZA': return ZA;
      case 'ZM': return ZM;
      case 'ZW': return ZW;
    }
    return [];
  }
}
